# [build]
#   publish = "public"
#   command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.49"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.49"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.49"